const mongoose= require("mongoose");
const users= mongoose.Schema({
    first_name:{
        type:String,
        required:true,
        trim:true
    },
    last_name:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String,
        required:true
    },
    
    email_id:{
        type:String,
        required:true,
        trim:true,
    },
    role:{
        type:String,
        required:true,
        enum:["Admin","Student","Instructor"],
    },
    profile:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"profile",
        required:true
    },
    cources:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"cource",  
    }],
    image:{
        type:String,
        required:true,
        trim:true
    },
    cource_progress:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"cource_progress"
    }],
    contact_no:{
        type:Number,
        trim:true,
    },
    reset_token:{
        type:String,
        trim:true
    },
    reset_token_expires_time:{
        type:Date
    }
});
module.exports= mongoose.model("user",users);